This will specify a readme for the repo
mb3online/react-style-manager pull request #5
Opened 2016-12-14 14:39 UTC by pvienneau

2016-12-14 14:42 UTC, devriestyler approved these changes

2016-12-14 14:56 UTC, andrew09 requested changes
Looks good. Just 1 comment.

2016-12-14 14:56 UTC, andrew09 commented on README.md
> +1. Run `npm install react-style-manager --save` to install the package in your application.
Shouldn't this be yarn? and not --save?

2016-12-14 14:57 UTC, andrew09 commented
Pat, can we rename this to be more in line with what it is doing?

2016-12-14 15:48 UTC, pvienneau commented on README.md
> +1. Run `npm install react-style-manager --save` to install the package in your application.
@andrew09 has been veto'd by @devriestyler.

2016-12-14 15:50 UTC, ericadamski approved these changes

2016-12-15 16:02 UTC, andrew09 approved these changes
👍

2016-12-16 14:43 UTC, merged